## NumPy Playground

Reference guide can be found [here](https://nustat.github.io/DataScience_Intro_python/NumPy.html)

## Creating a NumPy array

In [2]:
import numpy as np

my_list = [0, 1, 2, 3, 4, 5]
numpy_array = np.array(my_list)

print(type(numpy_array))
print(numpy_array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [3]:
another_numpy_array = np.array([[1, 2], [3, 4]])
print(another_numpy_array)

[[1 2]
 [3 4]]


---

## NumPy array to list

Suppose you want to go from a numpy array back to a list

In [4]:
list1 = [0, 1, 2, 3, 4, 5]
numpy_array = np.array(list1)

print(type((numpy_array)))
print(numpy_array)

list2 = numpy_array.tolist()
print(type(list2))
print(list2)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]
<class 'list'>
[0, 1, 2, 3, 4, 5]


---

## Why Use NumPy?

- Efficient multidimensional array
- Fast array-oriented arithmetic ops
- Flexible broadcasting capabilities
- Mathematical functions for arrays
- Tools for reading/writing data to disk
- Linear algebra, random number generation, and Fourier transformations
- NumPy arrays are also memory efficient!

### Important difference between Python lists and NumPy arrays

- NumPy arrays can handle vectorised ops, whereas Python lists cannot
- If you apply a function to a numpy array, it is performed on every item in the array, whereas on a list, it applies to the whole list

In [5]:
# normal python, will throw an error
list = [0, 1, 2, 3, 4]
list = list + 2

TypeError: can only concatenate list (not "int") to list

In [6]:
list = [0, 1, 2, 3, 4, 5]

np_arr = np.array(list)
np_arr = np_arr + 2

# Notice how it adds 2 to every item in np_arr but leaves list untouched!
print(np_arr)
print(list)

[2 3 4 5 6 7]
[0, 1, 2, 3, 4, 5]


---

## NumPy Array: Basic Attributes

In [7]:
np_arr_example = np.array([[1, 2, 3], [4, 5, 6]])

print(np_arr_example)

[[1 2 3]
 [4 5 6]]


### ndim Shows the number of dimensions

In [8]:
print(np_arr_example.ndim)

2


### shape returns a tuple of integers indicating the size of the array in each dimension

In [9]:
print(np_arr_example.shape)

(2, 3)


### size returns the total number of elements in the array

print(np_arr_example.size)

### dtype describes the data type of the elements in the array. You can create or specify dtypes using standard Python types

In [11]:
print(np_arr_example.dtype)

int64


---

## More NumPy Operations

## Logarithms

### Log10

In [12]:
np_arr_ex = np.array([1, 10, 100, 1000, 10000])

log10_arr = np.log10(np_arr_ex)

print(log10_arr)

[0. 1. 2. 3. 4.]


### Comparison (==)

In [14]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 3]])

# compares each element individually
print(arr1 == arr2)

[[False  True  True]
 [False False False]]


### Comparison (!=)

In [16]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 3]])

# compares each element individually
print(arr1 != arr2)

[[ True False False]
 [ True  True  True]]


### Comparison (>=)

In [17]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 3]])

# compares each element individually
print(arr1 >= arr2)

[[False  True  True]
 [ True  True  True]]


## Arithmetic Ops: Element-wise summation of arrays

In [18]:
arr1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 1, 2, 3]
])

arr2 = np.array([
    [11, 12, 13, 14],
    [15, 16, 17, 18],
    [19, 11, 12, 13]
])

#
print(arr1 + arr2)

[[12 14 16 18]
 [20 22 24 26]
 [28 12 14 16]]


---

## Broadcasting

Think of it as a shortcut that lets NumPy automatically stretch smaller arrays to match larger ones during math operations, without you having to write loops. In the following example, it works because they have the same number of columns (arr1 is 3x4 and arr2 is 1x4), so arr2 gets "stretched out" to match arr1.

In [19]:
arr1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 1, 2, 3]
])

arr2 = np.array([4, 5, 6, 7])

print(arr1 + arr2)

[[ 5  7  9 11]
 [ 9 11 13 15]
 [13  6  8 10]]


### Bad example

This doesn't work because arr1 is 3x3 and arr2 is 1x4, so there's no way to stretch arr2 to match arr1

In [22]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

## Concatenating Arrays
Note that the number of columns must match to concatenate. In this example, each is a 2x3 array so we can do this

In [26]:
arr1 = np.array([
    [1, 2, 3],
    [3, 4, 5]
])

arr2 = np.array([
    [2, 2, 3],
    [1, 2, 5]
])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[[1 2 3]
 [3 4 5]
 [2 2 3]
 [1 2 5]]


## tolist()
Converts a np array back to a Python list

In [28]:
arr1 = np.array([
    [1, 2, 3],
    [3, 4, 5]
])
arr2 = np.array([
    [2, 2, 3],
    [1, 2, 5]
])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

arr3.tolist()

[[1 2 3]
 [3 4 5]
 [2 2 3]
 [1 2 5]]


[[1, 2, 3], [3, 4, 5], [2, 2, 3], [1, 2, 5]]

---

## Review: Inspecting a NumPy Array

In [34]:
my_list = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
]

# by default this will be int, we are forcing the type to be float
np_arr = np.array(my_list, dtype='float')

print('Shape:', np_arr.shape)
print('Data type:', np_arr.dtype)
print('Size:', np_arr.size)
print('# Dimensions:', np_arr.ndim)

Shape: (3, 3)
Data type: float64
Size: 9
# Dimensions: 2


## Extracting Items from an array

In [39]:
my_list = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
]
np_arr = np.array(my_list, dtype='float')

# Note how it only grabs the last 2 parts of each matrix:
print("Whole:", np_arr)
print("Part:", np_arr[:2, :2])

Whole: [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Part: [[0. 1.]
 [3. 4.]]


## Boolean Index

In [42]:
my_list = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
]

np_arr = np.array(my_list, dtype='float')

# checks if each element is greater than 2
boo = np_arr > 2
print(boo)

[[False False False]
 [ True  True  True]
 [ True  True  True]]
